services:

  # Baza danych PostgreSQL.
  db:
    image: postgres:17
    restart: unless-stopped

    # Dane potrzebne do utworzenia i połączenia z bazą.
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    # Przechowuje dane bazy nawet po zatrzymaniu kontenera.
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis będzie używany przez Celery do obsługi kolejek zadań.
  redis:
    image: redis:7
    restart: unless-stopped

  # Aplikacja Django.
  web:
    build: .

    # Uruchamia serwer Django na porcie 8000.
    command: python manage.py runserver 0.0.0.0:8000

    # Udostępnia pliki projektu wewnątrz kontenera.
    volumes:
      - .:/app

    # Udostępnia port Django na komputerze.
    ports:
      - "8000:8000"

    # Pobiera zmienne środowiskowe z pliku .env.
    env_file:
      - .env

    # Django łączy się z kontenerem bazy danych.
    environment:
      DB_HOST: db
      DB_PORT: 5432

    # Kontener Django zależy od kontenera PostgreSQL.
    depends_on:
      - db
      - redis

  # Worker obsługujący kolejkę zamówień.
  celery_worker_orders:
    build: .
    command: celery -A myproject worker -l info -Q orders
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
      - redis

  # Worker obsługujący kolejkę powiadomień.
  celery_worker_notifications:
    build: .
    command: celery -A myproject worker -l info -Q notifications
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
      - redis

  # Celery Beat uruchamia zadania według harmonogramu.
  celery_beat:
    build: .
    command: celery -A myproject beat -l info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
      - redis

# Wolumen przechowujący dane PostgreSQL.
volumes:
  postgres_data:
